# Generated by Django 3.0.5 on 2020-05-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('created',), 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventsubscribers',
            options={'ordering': ('created',), 'verbose_name_plural': 'Event Subscribers'},
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='eventsubscribers',
            table='event_subscribers',
        ),
    ]
