# Generated by Django 3.0.5 on 2020-04-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200429_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_image',
            new_name='image',
        ),
    ]
