# Generated by Django 3.0.5 on 2020-04-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=250),
        ),
    ]
