# Generated by Django 3.0.5 on 2020-04-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200429_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='news',
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
