# Generated by Django 3.0.5 on 2020-04-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_gallery_museum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('created',), 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='museum',
            options={'ordering': ('created',), 'verbose_name_plural': 'Museum'},
        ),
        migrations.AlterModelTable(
            name='museum',
            table='museum',
        ),
    ]
