# Generated by Django 3.0.5 on 2020-04-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_auto_20200430_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=150), max_length=150),
        ),
    ]
