# Generated by Django 3.0.5 on 2020-05-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_museum_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryBook',
        ),
        migrations.AlterField(
            model_name='museum',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
