# Generated by Django 3.0.5 on 2020-05-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_auto_20200502_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
