# Generated by Django 3.0.5 on 2020-05-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorybook',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
    ]
