# Generated by Django 3.0.5 on 2020-05-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_categorybook_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='categorybook',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
