# Generated by Django 3.0.5 on 2020-05-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ('-subscribed',)},
        ),
        migrations.AlterModelTable(
            name='newsletter',
            table='newsletter',
        ),
    ]
